name: scorekeeper_biobuzz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  audioplayers: ^6.8.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/background_dark.png
  - assets/images/background.png
  - assets/images/white_logo_biobuzz.png
  - assets/images/background_windows.png
  - assets/sounds/3-2-1-go.mp3
  - assets/sounds/8s_pause.mp3
  - assets/sounds/endgame.mp3
  - assets/sounds/final.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
