name: Build APK, Windows EXE and Linux

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scorekeeper-BioBuzz-APK
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Prepare Installer Folder
        shell: powershell
        run: New-Item -Path "build\windows\installer" -ItemType Directory -Force

      - name: Build Inno Setup Installer
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer_script.iss

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scorekeeper-BioBuzz-Windows
          path: build\windows\installer\Scorekeeper_BioBuzz_Setup_v1.0.0.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Build Linux Release
        run: flutter build linux --release

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scorekeeper-BioBuzz-Linux
          path: build/linux/x64/release/bundle/